# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stage',
            name='entry',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
